# Desenvolvido por Guiherme de Souza na mentoria de migrations
version: '3.3'
services:
  node:
    # Nome da imagem
    image: node:16-alpine
    # Nome do container que vai ser criado
    container_name: sequelize_migration
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    command: sh
    # Diretório padrão de execução
    working_dir: /app
    ports: 
      - 3000:3000
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/app
  
  db:
    container_name: sequelize_db
    image: mysql:5.7
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'library'
    ports:
      - 3306:3306